import Foundation

/// The single policy deciding which pasteboard representations may cross the
/// clipboard channel.
///
/// Shared by every intake site — the guest agent's pasteboard poll and the
/// host window's Paste/drag gestures — so both ends of the channel apply
/// identical filtering and the rules stay in one place.
///
/// There is **no size cap**: every transfer is chunk-streamed to/from disk, so
/// a representation's size no longer gates whether it can cross. What remains
/// are identity skips — representation types that must never be sent or applied
/// regardless of size — and the empty-payload skip.
public enum ClipboardSnapshotPolicy {
    /// Why a representation was excluded from a snapshot.
    public enum SkipReason: Equatable, Sendable {
        /// `org.nspasteboard.*` marker types (TransientType, ConcealedType,
        /// AutoGeneratedType, …) are metadata flags, not content.
        case transientMarkerType

        /// File URLs, file promises, and legacy filename lists name
        /// host-side filesystem locations that are meaningless — or
        /// misleading — inside the guest, and promises require a
        /// sender-side callback flow that cannot cross the wire.
        case fileReferenceType

        /// Zero-byte representations carry no information.
        case emptyData
    }

    /// One excluded representation and the rule that excluded it.
    public struct Skipped: Equatable, Sendable {
        /// The excluded representation's UTI.
        public let uti: String

        /// The rule that excluded it.
        public let reason: SkipReason

        /// Creates a skip record.
        public init(uti: String, reason: SkipReason) {
            self.uti = uti
            self.reason = reason
        }
    }

    /// Result of evaluating a raw pasteboard snapshot.
    ///
    /// Never silently empty: when the input was non-empty but `content`
    /// is, `skipped` records why every representation was excluded.
    public struct Outcome: Sendable {
        /// The representations that survived every rule.
        public let content: ClipboardContent

        /// The representations excluded, with reasons.
        public let skipped: [Skipped]
    }

    /// `true` for types excluded by identity alone (`transientMarkerType` /
    /// `fileReferenceType`).
    ///
    /// Callable before reading any data so these skips cost nothing —
    /// intake sites should filter their type lists with this first, then
    /// read data only for the survivors.
    public static func shouldSkipBeforeReading(uti: String) -> Bool {
        skipReasonBeforeReading(uti: uti) != nil
    }

    /// Returns only the representations that are safe to apply to a pasteboard.
    ///
    /// Receive-side enforcement, symmetric with the send-side `evaluate(_:)`:
    /// compliant peers already filter at snapshot time, so anything caught here
    /// came from a buggy or malicious peer. It (1) drops the identity skips —
    /// without it a crafted payload could smuggle e.g. a `public.file-url` onto
    /// the receiving pasteboard behind a visible image representation — and
    /// (2) drops empty representations. Sizes are no longer gated: a streamed
    /// representation is bounded by free disk space, not a fixed cap.
    public static func sanitizedForApply(
        _ representations: [ClipboardContent.Representation]
    ) -> [ClipboardContent.Representation] {
        representations.filter { representation in
            if shouldSkipBeforeReading(uti: representation.uti) { return false }
            if representation.byteCount == 0 { return false }
            return true
        }
    }

    /// Applies every rule, in order, over (uti, data) pairs read from one pasteboard item.
    ///
    /// Operates on in-memory (uti, data) pairs read from a non-file pasteboard
    /// item — copied *files* take the disk-backed `.file` path and never pass
    /// through here. Dynamic (`dyn.*`) UTIs are deliberately kept: the encoding
    /// is a deterministic function of the original legacy type, so macOS↔macOS
    /// round-trips reproduce the exact type.
    public static func evaluate(_ raw: [(uti: String, data: Data)]) -> Outcome {
        var kept: [ClipboardContent.Representation] = []
        var skipped: [Skipped] = []

        for (uti, data) in raw {
            if let reason = skipReasonBeforeReading(uti: uti) {
                skipped.append(Skipped(uti: uti, reason: reason))
                continue
            }
            if data.isEmpty {
                skipped.append(Skipped(uti: uti, reason: .emptyData))
                continue
            }
            kept.append(ClipboardContent.Representation(uti: uti, data: data))
        }

        return Outcome(content: ClipboardContent(representations: kept), skipped: skipped)
    }

    private static func skipReasonBeforeReading(uti: String) -> SkipReason? {
        if uti.hasPrefix("org.nspasteboard.") {
            return .transientMarkerType
        }
        if uti == "public.file-url"
            || uti.hasPrefix("com.apple.pasteboard.promised-file")
            || uti.hasPrefix("com.apple.NSFilePromise")
            || uti == "NSFilenamesPboardType"
        {
            return .fileReferenceType
        }
        return nil
    }
}
