import Foundation
import os

/// Static accessors for the Kernova guest agent that the host bundles in its
/// Resources directory.
///
/// The agent's version is the source of truth: a build phase extracts
/// `CFBundleShortVersionString` from the built `KernovaGuestAgent` binary's
/// embedded Info.plist and writes it to
/// `Kernova.app/Contents/Resources/KernovaGuestAgentVersion.txt`. Reading from
/// that sidecar at runtime guarantees the host can never claim to bundle a
/// version different from what actually ships in the DMG.
enum KernovaGuestAgentInfo {

    private static let logger = Logger(subsystem: "com.kernova.app", category: "KernovaGuestAgentInfo")

    /// Filename of the version sidecar in `Kernova.app/Contents/Resources/`.
    private static let versionResourceName = "KernovaGuestAgentVersion"
    private static let versionResourceExtension = "txt"

    /// Filename of the installer DMG in `Kernova.app/Contents/Resources/`.
    private static let dmgResourceName = "KernovaGuestAgent"
    private static let dmgResourceExtension = "dmg"

    /// The version of the guest agent embedded in this build of the host.
    ///
    /// Resolved from the bundled `KernovaGuestAgentVersion.txt` resource. The
    /// resource is generated by the "Package Guest Agent DMG" build phase and
    /// is always present in a correctly-built `Kernova.app`. Returns `nil` only
    /// when the resource is missing, which indicates a build-system regression.
    static let bundledVersion: String? = {
        guard let url = Bundle.main.url(
            forResource: versionResourceName,
            withExtension: versionResourceExtension
        ) else {
            logger.fault("KernovaGuestAgentVersion.txt missing from app bundle")
            assertionFailure("KernovaGuestAgentVersion.txt missing — check 'Package Guest Agent DMG' build phase outputs")
            return nil
        }
        do {
            let raw = try String(contentsOf: url, encoding: .utf8)
            let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else {
                logger.fault("KernovaGuestAgentVersion.txt is empty")
                assertionFailure("KernovaGuestAgentVersion.txt is empty")
                return nil
            }
            return trimmed
        } catch {
            logger.fault("Failed to read KernovaGuestAgentVersion.txt: \(error.localizedDescription, privacy: .public)")
            assertionFailure("Failed to read KernovaGuestAgentVersion.txt: \(error.localizedDescription)")
            return nil
        }
    }()

    /// Filesystem URL of the guest agent installer DMG, or `nil` if missing.
    static var installerDiskImageURL: URL? {
        Bundle.main.url(
            forResource: dmgResourceName,
            withExtension: dmgResourceExtension
        )
    }
}
