import Foundation
import KernovaKit
import os

/// Putting a file where a shell loads the `kernova` tool's completions from.
///
/// The file loads them *from the tool*, the way the symlink points at the
/// bundled binary rather than copying it: what Tab offers is then generated by
/// whichever tool is on the `PATH` at the time, so a release that adds a verb
/// needs nothing reinstalled. A file holding the generated script instead would
/// be a snapshot of one version's grammar.
enum ShellCompletionInstaller {
    /// A shell Kernova can write a loader for.
    enum Shell: String, CaseIterable {
        case zsh
        case bash
        case fish

        /// What this shell calls the file it loads `kernova`'s completions
        /// from.
        var fileName: String {
            switch self {
            case .zsh: "_kernova"
            case .bash: "kernova"
            case .fish: "kernova.fish"
            }
        }

        /// Where this shell looks for that file without being told to.
        ///
        /// zsh's is a system path because that is the one entry every zsh
        /// carries in `fpath` already; the other two are per-user because that
        /// is where bash-completion and fish look first.
        var defaultDirectory: URL {
            switch self {
            case .zsh:
                URL(fileURLWithPath: "/usr/local/share/zsh/site-functions", isDirectory: true)
            case .bash:
                UserHome.url.appending(
                    path: ".local/share/bash-completion/completions", directoryHint: .isDirectory)
            case .fish:
                UserHome.url.appending(
                    path: ".config/fish/completions", directoryHint: .isDirectory)
            }
        }

        /// The whole file.
        ///
        /// Each one asks the tool for its script and loads it, and each does
        /// nothing at all when no `kernova` is on the `PATH` — a shell whose
        /// startup is broken by a tool the user removed would be worse than no
        /// completions.
        ///
        /// zsh's calls `_kernova` itself rather than leaving it to the
        /// generated script's own self-call: that call is guarded by
        /// `funcstack[1]`, which `eval` pushes a frame in front of, so without
        /// this the first Tab only registers the function and a second is
        /// needed to see any candidates. The guard variable is what keeps a
        /// tool that answers nothing from recursing into this file forever.
        var loaderScript: String {
            switch self {
            case .zsh:
                """
                #compdef kernova
                (( $+commands[kernova] )) || return 1
                (( $+_kernova_loading )) && return 1
                typeset -g _kernova_loading=1
                eval "$(kernova --generate-completion-script zsh 2>/dev/null)"
                _kernova "$@"
                local ret=$?
                unset _kernova_loading
                return ret

                """
            case .bash:
                """
                command -v kernova >/dev/null || return 0
                eval "$(kernova --generate-completion-script bash 2>/dev/null)"

                """
            case .fish:
                """
                type -q kernova; and kernova --generate-completion-script fish | source

                """
            }
        }
    }

    /// Why an install did not happen.
    enum InstallFailure: Error, Equatable {
        /// The destination cannot be written, grant or no grant.
        case unwritable(String)
    }

    /// Writes `shell`'s loader to `destination`.
    ///
    /// Whatever is there is replaced: the panel has already asked about that,
    /// and reinstalling over an older loader is the one thing somebody
    /// installing a second time means to do. A plain write rather than an
    /// atomic one, so the only path touched is the one the panel returned.
    ///
    /// - Throws: ``InstallFailure``.
    static func install(_ shell: Shell, at destination: URL) throws {
        let path = destination.path(percentEncoded: false)
        do {
            try Data(shell.loaderScript.utf8).write(to: destination)
        } catch {
            Self.logger.error(
                "Could not install \(shell.rawValue, privacy: .public) completions at \(path, privacy: .public): \(error.localizedDescription, privacy: .public)"
            )
            throw InstallFailure.unwritable(error.localizedDescription)
        }
        Self.logger.notice(
            "Installed \(shell.rawValue, privacy: .public) completions at \(path, privacy: .public)"
        )
    }

    /// The command that does by hand what the panel does.
    ///
    /// One line, because it is meant to be selected and pasted: `printf` takes
    /// the loader a line at a time rather than a here-document, which a
    /// single-line callout cannot hold.
    static func manualCommand(for shell: Shell, at destination: URL) -> String {
        let lines = shell.loaderScript
            .split(separator: "\n", omittingEmptySubsequences: false)
            .dropLast()  // the trailing newline's empty tail
            .map { quoted(String($0)) }
            .joined(separator: " ")
        // `deletingLastPathComponent` leaves a trailing separator behind, which
        // the command reads better without.
        var folder = destination.deletingLastPathComponent().path(percentEncoded: false)
        if folder.count > 1, folder.hasSuffix("/") { folder.removeLast() }
        let directory = quoted(folder)
        let file = quoted(destination.path(percentEncoded: false))
        return "mkdir -p \(directory) && printf '%s\\n' \(lines) > \(file)"
    }

    /// `text` as one shell word, safe inside any of them.
    private static func quoted(_ text: String) -> String {
        "'" + text.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private static let logger = Logger(
        subsystem: "app.kernova", category: "ShellCompletionInstaller")
}
