import Foundation
import KernovaKit
import os

/// Putting a file where a shell loads the `kernova` tool's completions from.
///
/// The file loads them *from the tool*, the way the symlink points at the
/// bundled binary rather than copying it: what Tab offers is then generated by
/// whichever tool is on the `PATH` at the time, so a release that adds a verb
/// needs nothing reinstalled. A file holding the generated script instead would
/// be a snapshot of one version's grammar.
enum ShellCompletionInstaller {
    /// A shell Kernova can write a loader for.
    enum Shell: String, CaseIterable {
        case zsh
        case bash
        case fish

        /// What this shell calls the file it loads `kernova`'s completions
        /// from.
        var fileName: String {
            switch self {
            case .zsh: "_kernova"
            case .bash: "kernova"
            case .fish: "kernova.fish"
            }
        }

        /// Where this shell looks for that file without being told to.
        ///
        /// bash-completion and fish each look in a folder under the user's own
        /// home. zsh's `fpath` entries are system paths, and the ones on a Mac
        /// belong to root — `/usr/local/share` does not exist at all on a stock
        /// one — so a `site-functions` a package manager already made the
        /// user's own is preferred and `~/.zsh/completions` is the answer when
        /// there is none. That last one is on nobody's `fpath` until they add
        /// it, which the pane says.
        var defaultDirectory: URL {
            switch self {
            case .zsh:
                ShellCompletionInstaller.siteFunctions
                    ?? UserHome.url.appending(
                        path: ".zsh/completions", directoryHint: .isDirectory)
            case .bash:
                UserHome.url.appending(
                    path: ".local/share/bash-completion/completions", directoryHint: .isDirectory)
            case .fish:
                UserHome.url.appending(
                    path: ".config/fish/completions", directoryHint: .isDirectory)
            }
        }

        /// The whole file.
        ///
        /// Each one asks the tool for its script and loads it, and each does
        /// nothing at all when no `kernova` is on the `PATH` — a shell whose
        /// startup is broken by a tool the user removed would be worse than no
        /// completions.
        ///
        /// zsh's calls `_kernova` itself rather than leaving it to the
        /// generated script's own self-call: that call is guarded by
        /// `funcstack[1]`, which `eval` pushes a frame in front of, so without
        /// this the first Tab only registers the function and a second is
        /// needed to see any candidates. The guard is what keeps a tool that
        /// answers nothing from recursing into this file forever, and it is
        /// `local` so that zsh unwinds it however the function ends — the
        /// recursive call still sees it, which is the whole job.
        var loaderScript: String {
            switch self {
            case .zsh:
                """
                #compdef kernova
                (( $+commands[kernova] )) || return 1
                (( $+_kernova_loading )) && return 1
                local _kernova_loading=1
                eval "$(kernova --generate-completion-script zsh 2>/dev/null)"
                _kernova "$@"

                """
            case .bash:
                """
                command -v kernova >/dev/null || return 0
                eval "$(kernova --generate-completion-script bash 2>/dev/null)"

                """
            case .fish:
                """
                type -q kernova; and kernova --generate-completion-script fish | source

                """
            }
        }
    }

    /// A `site-functions` on this Mac the user can write into, `nil` when
    /// neither is there or both are root's.
    static var siteFunctions: URL? {
        let candidates = [
            "/opt/homebrew/share/zsh/site-functions",
            "/usr/local/share/zsh/site-functions",
        ]
        guard let path = candidates.first(where: isUserWritableDirectory) else { return nil }
        return URL(fileURLWithPath: path, isDirectory: true)
    }

    /// Whether the user could create a file in the directory at `path`.
    ///
    /// Read from the directory's own owner and mode rather than asked with
    /// `access`, which answers for *this* process: the panel's grant is what
    /// lets the app write outside its container, and the question left after
    /// that is whether the filesystem would refuse the user.
    static func isUserWritableDirectory(_ path: String) -> Bool {
        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(atPath: path, isDirectory: &isDirectory),
            isDirectory.boolValue,
            let attributes = try? FileManager.default.attributesOfItem(atPath: path),
            let permissions = attributes[.posixPermissions] as? Int
        else { return false }
        if permissions & 0o002 != 0 { return true }
        guard let owner = attributes[.ownerAccountID] as? uid_t, owner == getuid() else {
            return false
        }
        return permissions & 0o200 != 0
    }

    /// The deepest folder on `directory`'s path that is there.
    ///
    /// A save panel silently ignores a `directoryURL` that does not exist and
    /// opens wherever it was last, so it is pointed at the closest real
    /// ancestor and told the rest of the path in its message.
    static func existingAncestor(of directory: URL) -> URL {
        var candidate = directory
        while candidate.pathComponents.count > 1 {
            var isDirectory: ObjCBool = false
            if FileManager.default.fileExists(
                atPath: candidate.path(percentEncoded: false), isDirectory: &isDirectory),
                isDirectory.boolValue
            {
                return candidate
            }
            candidate = candidate.deletingLastPathComponent()
        }
        return URL(fileURLWithPath: "/", isDirectory: true)
    }

    /// Writes `shell`'s loader to `destination`.
    ///
    /// Whatever is there is replaced: the panel has already asked about that,
    /// and reinstalling over an older loader is the one thing somebody
    /// installing a second time means to do. A plain write rather than an
    /// atomic one, so the only path touched is the one the panel returned.
    ///
    /// - Throws: ``InstallFailure``.
    static func install(_ shell: Shell, at destination: URL) throws {
        let path = destination.path(percentEncoded: false)
        do {
            try Data(shell.loaderScript.utf8).write(to: destination)
        } catch {
            Self.logger.error(
                "Could not install \(shell.rawValue, privacy: .public) completions at \(path, privacy: .public): \(error.localizedDescription, privacy: .public)"
            )
            throw InstallFailure.unwritable(error.localizedDescription)
        }
        Self.logger.notice(
            "Installed \(shell.rawValue, privacy: .public) completions at \(path, privacy: .public)"
        )
    }

    /// The command that does by hand what the panel does.
    ///
    /// One line, because it is meant to be selected and pasted: `printf` takes
    /// the loader a line at a time rather than a here-document, which a
    /// single-line callout cannot hold.
    static func manualCommand(for shell: Shell, at destination: URL) -> String {
        let lines = shell.loaderScript
            .split(separator: "\n", omittingEmptySubsequences: false)
            .dropLast()  // the trailing newline's empty tail
            .map { quoted(String($0)) }
            .joined(separator: " ")
        // `deletingLastPathComponent` leaves a trailing separator behind, which
        // the command reads better without.
        var folder = destination.deletingLastPathComponent().path(percentEncoded: false)
        if folder.count > 1, folder.hasSuffix("/") { folder.removeLast() }
        let directory = quoted(folder)
        let file = quoted(destination.path(percentEncoded: false))
        return "mkdir -p \(directory) && printf '%s\\n' \(lines) > \(file)"
    }

    /// `text` as one shell word, safe inside any of them.
    private static func quoted(_ text: String) -> String {
        "'" + text.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private static let logger = Logger(
        subsystem: "app.kernova", category: "ShellCompletionInstaller")
}
