import AppKit
import Foundation
import KernovaKit
import Testing
import UniformTypeIdentifiers

@testable import Kernova

@Suite("ClipboardPasteboardIntake")
@MainActor
struct ClipboardPasteboardIntakeTests {
    /// Fresh uniquely-named pasteboard so tests never touch `.general`.
    private func makeScratchPasteboard() -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("kernova-test-\(UUID().uuidString)"))
    }

    private func write(
        _ representations: [(uti: String, data: Data)], to pasteboard: NSPasteboard
    ) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        for representation in representations {
            item.setData(
                representation.data,
                forType: NSPasteboard.PasteboardType(rawValue: representation.uti))
        }
        pasteboard.writeObjects([item])
    }

    private func makeTempFile(name: String, contents: Data) throws -> URL {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("kernova-intake-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(name)
        try contents.write(to: url)
        return url
    }

    private func makePNG() throws -> Data {
        let rep = try #require(
            NSBitmapImageRep(
                bitmapDataPlanes: nil, pixelsWide: 2, pixelsHigh: 2,
                bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0
            ))
        return try #require(rep.representation(using: .png, properties: [:]))
    }

    /// Resolves a `.pendingFiles` outcome by performing the async file read.
    ///
    /// Lets a file-URL intake test read the same as before the byte read moved
    /// off the main actor; non-file results pass through unchanged.
    private func resolve(
        _ result: ClipboardIntakeResult, allowsBinary: Bool
    ) -> ClipboardIntakeResult {
        guard case .pendingFiles(let urls) = result else { return result }
        return ClipboardPasteboardIntake.read(filesAt: urls, allowsBinary: allowsBinary)
    }

    // MARK: - Generic pasteboard reads

    @Test("text on the pasteboard becomes text content")
    func textIntake() {
        let pasteboard = makeScratchPasteboard()
        write([(uti: ClipboardContent.utf8TextUTI, data: Data("hello".utf8))], to: pasteboard)

        guard
            case .content(let content, let note) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.text == "hello")
        #expect(note == nil)
    }

    // MARK: - org.nspasteboard.* marker handling

    @Test("a concealed-marked snapshot still yields content, flagged isConcealed")
    func concealedIntake() {
        let pasteboard = makeScratchPasteboard()
        write(
            [
                (uti: "org.nspasteboard.ConcealedType", data: Data([1])),
                (uti: ClipboardContent.utf8TextUTI, data: Data("hunter2".utf8)),
            ], to: pasteboard)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.isConcealed)
        // The secret bytes still cross so the user can paste them into the guest.
        #expect(content.text == "hunter2")
    }

    @Test("a concealed snapshot conceals over the text-only transport too")
    func concealedTextOnlyIntake() {
        let pasteboard = makeScratchPasteboard()
        write(
            [
                (uti: "org.nspasteboard.ConcealedType", data: Data([1])),
                (uti: ClipboardContent.utf8TextUTI, data: Data("hunter2".utf8)),
            ], to: pasteboard)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: false)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.isConcealed)
        #expect(content.text == "hunter2")
    }

    @Test(
        "a transient or auto-generated snapshot is rejected wholesale",
        arguments: ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"])
    func suppressedIntake(marker: String) {
        let pasteboard = makeScratchPasteboard()
        write(
            [
                (uti: marker, data: Data([1])),
                (uti: ClipboardContent.utf8TextUTI, data: Data("noise".utf8)),
            ], to: pasteboard)

        guard
            case .rejected = ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected rejection for \(marker)")
            return
        }
    }

    @Test("multiple representations are all taken, in order")
    func multiRepIntake() throws {
        let pasteboard = makeScratchPasteboard()
        let png = try makePNG()
        write(
            [
                (uti: UTType.png.identifier, data: png),
                (uti: ClipboardContent.utf8TextUTI, data: Data("caption".utf8)),
            ], to: pasteboard)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(
            content.representations.map(\.uti) == [
                UTType.png.identifier, ClipboardContent.utf8TextUTI,
            ])
        #expect(content.representations.first?.inMemoryData == png)
    }

    @Test("flat-RTFD is captured alongside plain RTF and preferred for rich text")
    func flatRTFDCapturedAndPreferred() throws {
        // A TextEdit rich copy with an inline image carries both flat-RTFD (the
        // image-bearing flavor) and a text-only plain RTF. Intake must keep
        // flat-RTFD (it is not a skipped/file-reference type) and order it ahead
        // of plain RTF so the richer flavor wins downstream.
        let pasteboard = makeScratchPasteboard()
        let rtfd = Data("rtfd-with-image".utf8)
        write(
            [
                (uti: UTType.flatRTFD.identifier, data: rtfd),
                (uti: UTType.rtf.identifier, data: Data("{\\rtf1}".utf8)),
                (uti: ClipboardContent.utf8TextUTI, data: Data("plain".utf8)),
            ], to: pasteboard)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        let utis = content.representations.map(\.uti)
        let flatIndex = try #require(utis.firstIndex(of: UTType.flatRTFD.identifier))
        let rtfIndex = try #require(utis.firstIndex(of: UTType.rtf.identifier))
        #expect(flatIndex < rtfIndex)
        #expect(content.richTextRepresentation?.uti == UTType.flatRTFD.identifier)
        #expect(content.richTextRepresentation?.inMemoryData == rtfd)
    }

    @Test("empty pasteboard is rejected")
    func emptyPasteboardRejected() {
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()

        guard case .rejected = ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected rejection for empty pasteboard")
            return
        }
    }

    @Test("text-only transport takes only the text representation")
    func textOnlyTransport() throws {
        let pasteboard = makeScratchPasteboard()
        let png = try makePNG()
        write(
            [
                (uti: UTType.png.identifier, data: png),
                (uti: ClipboardContent.utf8TextUTI, data: Data("caption".utf8)),
            ], to: pasteboard)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: false)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.map(\.uti) == [ClipboardContent.utf8TextUTI])
    }

    @Test("text-only transport rejects image-only content with a clear message")
    func textOnlyTransportRejectsImage() throws {
        let pasteboard = makeScratchPasteboard()
        write([(uti: UTType.png.identifier, data: try makePNG())], to: pasteboard)

        guard
            case .rejected(let message) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: false)
        else {
            Issue.record("Expected rejection")
            return
        }
        #expect(message == ClipboardPasteboardIntake.textOnlyTransportMessage)
    }

    @Test("filtered-only content is rejected, not silently emptied")
    func filteredOnlyRejected() {
        let pasteboard = makeScratchPasteboard()
        write(
            [(uti: "org.nspasteboard.TransientType", data: Data([1]))], to: pasteboard)

        guard case .rejected = ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected rejection")
            return
        }
    }

    @Test("a large inline representation is kept (no size cap)")
    func largeInlineRepresentationKept() {
        // The greedy budget and per-rep cap are gone — streaming bounds size by
        // free disk, not a fixed limit, so a large inline rep survives intake.
        let pasteboard = makeScratchPasteboard()
        write(
            [
                (uti: UTType.tiff.identifier, data: Data(count: 8 * 1024 * 1024)),
                (uti: ClipboardContent.utf8TextUTI, data: Data("small".utf8)),
            ], to: pasteboard)

        guard
            case .content(let content, let note) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(
            content.representations.map(\.uti) == [
                UTType.tiff.identifier, ClipboardContent.utf8TextUTI,
            ])
        #expect(note == nil)
    }

    // MARK: - File URL expansion

    @Test("read(from:) defers a file URL to .pendingFiles so the bytes read off-actor")
    func readFromDefersFileToPendingFiles() throws {
        let url = try makeTempFile(name: "deferred.txt", contents: Data("x".utf8))
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(url.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([item])

        // The bytes are NOT read synchronously: read(from:) returns the URLs for
        // the caller to read off the main actor via read(filesAt:).
        guard
            case .pendingFiles(let pending) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .pendingFiles")
            return
        }
        #expect(pending.map(\.path) == [url.path])
    }

    @Test("read(from:) returns every item's file URL as .pendingFiles, in order")
    func readFromMultipleFiles() throws {
        let a = try makeTempFile(name: "a.txt", contents: Data("a".utf8))
        let b = try makeTempFile(name: "b.txt", contents: Data("b".utf8))
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let itemA = NSPasteboardItem()
        itemA.setString(a.absoluteString, forType: .fileURL)
        let itemB = NSPasteboardItem()
        itemB.setString(b.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([itemA, itemB])

        guard
            case .pendingFiles(let urls) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .pendingFiles")
            return
        }
        #expect(urls.map(\.lastPathComponent) == ["a.txt", "b.txt"])
    }

    @Test("read(filesAt:) builds one ordered filename rep per file")
    func readFilesAtMultiple() throws {
        let a = try makeTempFile(name: "one.txt", contents: Data("one".utf8))
        let b = try makeTempFile(name: "two.bin", contents: Data([0, 1, 2]))

        guard
            case .content(let content, let note) = ClipboardPasteboardIntake.read(
                filesAt: [a, b], allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.count == 2)
        #expect(content.representations.map(\.filename) == ["one.txt", "two.bin"])
        #expect(content.representations[0].fileURL == a)
        #expect(content.representations[1].byteCount == 3)
        #expect(note == nil)
    }

    @Test("read(filesAt:) skips an unreadable file with a note, keeping the rest")
    func readFilesAtSkipsUnreadable() throws {
        let good = try makeTempFile(name: "good.txt", contents: Data("ok".utf8))
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(UUID().uuidString)-missing.txt")

        guard
            case .content(let content, let note) = ClipboardPasteboardIntake.read(
                filesAt: [good, missing], allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.map(\.filename) == ["good.txt"])
        #expect(note != nil)
    }

    @Test("read(filesAt:) rejects when every file is unreadable")
    func readFilesAtAllFail() {
        let missing1 = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(UUID().uuidString)-m1")
        let missing2 = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(UUID().uuidString)-m2")

        guard
            case .rejected = ClipboardPasteboardIntake.read(
                filesAt: [missing1, missing2], allowsBinary: true)
        else {
            Issue.record("Expected rejection")
            return
        }
    }

    @Test("read(filesAt:) on a text-only transport is rejected")
    func readFilesAtTextOnlyRejected() throws {
        let a = try makeTempFile(name: "a.txt", contents: Data("a".utf8))
        guard
            case .rejected(let message) = ClipboardPasteboardIntake.read(
                filesAt: [a], allowsBinary: false)
        else {
            Issue.record("Expected rejection")
            return
        }
        #expect(message == ClipboardPasteboardIntake.textOnlyTransportMessage)
    }

    @Test("dragged text file crosses as a disk-backed file representation (name + size)")
    func textFileIntake() throws {
        // A copied/dragged .txt is "the file": it crosses as a disk-backed
        // representation tagged with the content UTI and name; its bytes stream
        // on demand and are never read at intake.
        let contents = Data("file text".utf8)
        let url = try makeTempFile(name: "note.txt", contents: contents)
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(url.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([item])

        guard
            case .content(let content, _) = resolve(
                ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true),
                allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.count == 1)
        #expect(content.representations[0].filename == "note.txt")
        #expect(content.representations[0].byteCount == contents.count)
        #expect(content.representations[0].fileURL == url)
        #expect(content.representations[0].inMemoryData == nil)  // never read at intake
    }

    @Test("dragged image file becomes a disk-backed image representation")
    func imageFileIntake() throws {
        let png = try makePNG()
        let url = try makeTempFile(name: "image.png", contents: png)
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(url.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([item])

        guard
            case .content(let content, _) = resolve(
                ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true),
                allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.count == 1)
        #expect(UTType(content.representations[0].uti)?.conforms(to: .image) == true)
        #expect(content.representations[0].byteCount == png.count)
        #expect(content.representations[0].fileURL == url)
        // The filename is carried so the guest can paste it as a file.
        #expect(content.representations[0].filename == "image.png")
    }

    @Test("dragged non-image file crosses as a disk-backed file representation")
    func nonImageFileCrossesAsFile() throws {
        let contents = Data([0x00, 0x01])
        let url = try makeTempFile(name: "blob.bin", contents: contents)
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(url.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([item])

        guard
            case .content(let content, _) = resolve(
                ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true),
                allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.count == 1)
        #expect(content.representations[0].filename == "blob.bin")
        #expect(content.representations[0].byteCount == contents.count)
        #expect(content.representations[0].fileURL == url)
    }

    @Test("read(filesAt:) resolves a single image file directly — the promise-receipt path")
    func directFileReadImage() throws {
        let png = try makePNG()
        let url = try makeTempFile(name: "promised.png", contents: png)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                filesAt: [url], allowsBinary: true)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.count == 1)
        #expect(content.representations[0].byteCount == png.count)
        #expect(content.representations[0].fileURL == url)
    }

    @Test("read(filesAt:) accepts a file far larger than the old cap (no size limit)")
    func directFileReadLargeAccepted() throws {
        // A file over the old 100 MiB per-rep cap is no longer rejected — it
        // becomes a disk-backed rep whose bytes stream on demand. A sparse file
        // keeps the test fast.
        let url = try makeTempFile(name: "huge.bin", contents: Data())
        let handle = try FileHandle(forWritingTo: url)
        try handle.truncate(atOffset: 200 * 1024 * 1024)  // 200 MiB sparse
        try handle.close()

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                filesAt: [url], allowsBinary: true)
        else {
            Issue.record("Expected content (no size cap)")
            return
        }
        #expect(content.representations.first?.byteCount == 200 * 1024 * 1024)
    }

    @Test("dragged image file on a text-only transport is rejected")
    func imageFileTextOnlyRejected() throws {
        let url = try makeTempFile(name: "image.png", contents: try makePNG())
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(url.absoluteString, forType: .fileURL)
        pasteboard.writeObjects([item])

        guard
            case .rejected(let message) = resolve(
                ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: false),
                allowsBinary: false)
        else {
            Issue.record("Expected rejection")
            return
        }
        #expect(message == ClipboardPasteboardIntake.textOnlyTransportMessage)
    }

    // MARK: - Folder archiving (Phase 2)

    private func makeStaging() -> ClipboardFileStaging {
        ClipboardFileStaging(
            label: "intake-test-\(UUID().uuidString)",
            tempRoot: FileManager.default.temporaryDirectory.appendingPathComponent(
                UUID().uuidString, isDirectory: true))
    }

    private func makeTempFolder(name: String, files: [(String, Data)]) throws -> URL {
        let parent = FileManager.default.temporaryDirectory
            .appendingPathComponent("kernova-intake-folder-\(UUID().uuidString)", isDirectory: true)
        let folder = parent.appendingPathComponent(name, isDirectory: true)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        for (fileName, data) in files {
            try data.write(to: folder.appendingPathComponent(fileName))
        }
        return folder
    }

    @Test("a copied folder is archived into one directory representation")
    func folderArchivedAsDirectoryRep() async throws {
        let staging = makeStaging()
        defer { staging.sweep() }
        let folder = try makeTempFolder(
            name: "MyFolder", files: [("a.txt", Data("a".utf8)), ("b.txt", Data("bee".utf8))])
        defer { try? FileManager.default.removeItem(at: folder.deletingLastPathComponent()) }

        guard
            case .content(let content, let note) = await ClipboardPasteboardIntake.read(
                filesAt: [folder], allowsBinary: true, staging: staging, generation: 1, dirTree: false)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(note == nil)
        #expect(content.representations.count == 1)
        let rep = try #require(content.representations.first)
        #expect(rep.isDirectory)
        #expect(rep.uti == UTType.folder.identifier)
        #expect(rep.filename == "MyFolder")
        #expect(rep.byteCount > 0)
        // The rep points at a real `.aar` that extracts back to the original tree.
        let archiveURL = try #require(rep.fileURL)
        let dest = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: dest, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dest) }
        try ClipboardDirectoryArchive.extract(archiveAt: archiveURL, to: dest)
        #expect(
            try String(contentsOf: dest.appendingPathComponent("b.txt"), encoding: .utf8) == "bee")
    }

    @Test("with the dir-tree capability, a copied folder is a source-directory rep (no archive)")
    func folderAsSourceDirectoryRepWithDirTree() async throws {
        let staging = makeStaging()
        defer { staging.sweep() }
        let folder = try makeTempFolder(
            name: "Tree", files: [("a.txt", Data("a".utf8)), ("b.txt", Data("bee".utf8))])
        defer { try? FileManager.default.removeItem(at: folder.deletingLastPathComponent()) }

        guard
            case .content(let content, _) = await ClipboardPasteboardIntake.read(
                filesAt: [folder], allowsBinary: true, staging: staging, generation: 1,
                dirTree: true)
        else {
            Issue.record("Expected content")
            return
        }
        let rep = try #require(content.representations.first)
        #expect(rep.isDirectory)
        #expect(rep.filename == "Tree")
        // A source-directory rep: the URL is the original folder, not a staged
        // `.aar`, and the byte count is a stat-walk estimate (1 + 3 bytes).
        #expect(rep.directorySourceURL == folder)
        #expect(rep.fileURL == nil)
        #expect(rep.byteCount == 4)
    }

    @Test("a mixed file + folder selection yields one rep each, in order")
    func mixedFileAndFolder() async throws {
        let staging = makeStaging()
        defer { staging.sweep() }
        let file = try makeTempFile(name: "plain.txt", contents: Data("hello".utf8))
        let folder = try makeTempFolder(name: "Docs", files: [("inside.txt", Data("x".utf8))])
        defer { try? FileManager.default.removeItem(at: folder.deletingLastPathComponent()) }

        guard
            case .content(let content, _) = await ClipboardPasteboardIntake.read(
                filesAt: [file, folder], allowsBinary: true, staging: staging, generation: 1, dirTree: false)
        else {
            Issue.record("Expected content")
            return
        }
        #expect(content.representations.count == 2)
        #expect(content.representations[0].isDirectory == false)
        #expect(content.representations[0].filename == "plain.txt")
        #expect(content.representations[1].isDirectory)
        #expect(content.representations[1].filename == "Docs")
    }

    @Test("folder archiving on a text-only transport is rejected")
    func folderTextOnlyRejected() async throws {
        let staging = makeStaging()
        defer { staging.sweep() }
        let folder = try makeTempFolder(name: "F", files: [("a", Data("a".utf8))])
        defer { try? FileManager.default.removeItem(at: folder.deletingLastPathComponent()) }
        guard
            case .rejected = await ClipboardPasteboardIntake.read(
                filesAt: [folder], allowsBinary: false, staging: staging, generation: 1, dirTree: false)
        else {
            Issue.record("Expected rejection")
            return
        }
    }

    // MARK: - Screenshot thumbnail (promised file URL)

    @Test("a promised-file-url on disk is resolved as the image — the screenshot thumbnail mechanism")
    func promisedFileURLImage() throws {
        // The floating screenshot thumbnail is a promise drag: NO concrete
        // public.file-url, NO inline image bytes — only a promised-file-url
        // pointing at the temp file screencaptureui has already written, plus
        // a path-text fallback. The temp file exists during the drag.
        let png = try makePNG()
        let url = try makeTempFile(name: "Screenshot 2026 at 6.57.png", contents: png)
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(
            url.absoluteString,
            forType: NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url"))
        item.setString(url.path, forType: .string)  // the path-text fallback
        pasteboard.writeObjects([item])

        guard
            case .content(let content, _) = resolve(
                ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true),
                allowsBinary: true)
        else {
            Issue.record("Expected image content")
            return
        }
        #expect(content.representations.count == 1)
        #expect(UTType(content.representations[0].uti)?.conforms(to: .image) == true)
        #expect(content.representations[0].byteCount == png.count)
        #expect(content.representations[0].fileURL == url)
        // The decisive assertion: the path text must NOT leak as content.
        #expect(content.text == nil)
    }

    @Test("a promise drag with no on-disk file never leaks the path as text")
    func promiseWithoutFileNoPathLeak() {
        // Promise present, but the file isn't on disk and there's no inline
        // image — the path/url text reps are descriptors and must be dropped,
        // so the caller falls through to async promise receipt (a rejection
        // here), never showing the path string.
        let missing = "/var/folders/zz/missing-\(UUID().uuidString)/Screenshot.png"
        let pasteboard = makeScratchPasteboard()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(
            "file://" + missing,
            forType: NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url"))
        item.setData(
            Data("public.png".utf8),
            forType: NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-content-type"))
        item.setString(missing, forType: .string)
        pasteboard.writeObjects([item])

        guard case .rejected = ClipboardPasteboardIntake.read(from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected rejection — the path must not leak as text content")
            return
        }
    }

    @Test("a plain text drag (no file/promise) still becomes text")
    func plainTextDragStillText() {
        // Guard against over-reaching the file-context skip: a genuine text
        // drag has no file/promise types, so the text survives.
        let pasteboard = makeScratchPasteboard()
        write([(uti: ClipboardContent.utf8TextUTI, data: Data("just some text".utf8))], to: pasteboard)

        guard
            case .content(let content, _) = ClipboardPasteboardIntake.read(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected text content")
            return
        }
        #expect(content.text == "just some text")
    }
}
