import Foundation

/// The single policy deciding which pasteboard representations may cross the
/// clipboard channel.
///
/// Shared by every intake site — the guest agent's pasteboard poll and the
/// host window's Paste/drag gestures — so both ends of the channel apply
/// identical filtering and the rules stay in one place.
///
/// There is **no size cap**: every transfer is chunk-streamed to/from disk, so
/// a representation's size no longer gates whether it can cross. What remains
/// are identity skips — representation types that must never be sent or applied
/// regardless of size — and the empty-payload skip.
public enum ClipboardSnapshotPolicy {
    /// Why a representation was excluded from a snapshot.
    public enum SkipReason: Equatable, Sendable {
        /// An `org.nspasteboard.*` marker representation dropped from a synced
        /// payload. The markers (TransientType, ConcealedType, AutoGeneratedType,
        /// …) are metadata flags, not content, so their bytes never cross — but
        /// the content alongside them still does, unless the whole snapshot is
        /// suppressed (see `transientSnapshot` / `autoGeneratedSnapshot`).
        case transientMarkerType

        /// File URLs, file promises, and legacy filename lists name
        /// host-side filesystem locations that are meaningless — or
        /// misleading — inside the guest, and promises require a
        /// sender-side callback flow that cannot cross the wire.
        case fileReferenceType

        /// Zero-byte representations carry no information.
        case emptyData

        /// The whole snapshot was dropped because it carried an
        /// `org.nspasteboard.TransientType` marker — content the source app will
        /// restore or replace within seconds (a clipboard manager re-injecting a
        /// past entry, a TextExpander/Keyboard Maestro expansion), never a
        /// deliberate copy.
        case transientSnapshot

        /// The whole snapshot was dropped because it carried an
        /// `org.nspasteboard.AutoGeneratedType` marker — content an app placed
        /// with no copy intent (e.g. a Grammarly correction) that clipboard
        /// managers ignore by convention.
        case autoGeneratedSnapshot
    }

    /// One excluded representation and the rule that excluded it.
    public struct Skipped: Equatable, Sendable {
        /// The excluded representation's UTI.
        public let uti: String

        /// The rule that excluded it.
        public let reason: SkipReason

        /// Creates a skip record.
        public init(uti: String, reason: SkipReason) {
            self.uti = uti
            self.reason = reason
        }
    }

    /// Result of evaluating a raw pasteboard snapshot.
    ///
    /// Never silently empty: when the input was non-empty but `content`
    /// is, `skipped` records why every representation was excluded.
    public struct Outcome: Sendable {
        /// The representations that survived every rule.
        public let content: ClipboardContent

        /// The representations excluded, with reasons.
        public let skipped: [Skipped]
    }

    // MARK: - Marker types

    /// `org.nspasteboard.TransientType` — the source app will restore or replace
    /// the pasteboard within seconds; the content is never a deliberate copy.
    public static let transientMarkerUTI = "org.nspasteboard.TransientType"

    /// `org.nspasteboard.AutoGeneratedType` — content placed with no copy intent
    /// (e.g. a Grammarly correction); not something the user expects to paste.
    public static let autoGeneratedMarkerUTI = "org.nspasteboard.AutoGeneratedType"

    /// `org.nspasteboard.ConcealedType` — confidential content (password
    /// managers), synced so it can still be pasted but hidden from the host
    /// clipboard window's display.
    public static let concealedMarkerUTI = "org.nspasteboard.ConcealedType"

    /// What to do with an entire pasteboard snapshot, decided from its marker
    /// types before any data is read.
    ///
    /// Distinct from the per-representation `SkipReason` filtering: this is a
    /// whole-snapshot decision keyed off the `org.nspasteboard.*` privacy
    /// markers, applied identically by both intake sites — the host window's
    /// Paste/drag gestures and the guest agent's pasteboard poll.
    public enum SnapshotDisposition: Equatable, Sendable {
        /// Sync the snapshot normally (still subject to per-representation
        /// filtering via `evaluate`).
        case allow

        /// Sync the snapshot but mark its `ClipboardContent` concealed, so the
        /// host clipboard window hides it behind a placeholder while the bytes
        /// still cross to be pasted into the peer.
        case conceal

        /// Drop the entire snapshot so nothing crosses; the reason distinguishes
        /// the transient and auto-generated markers for user-facing messaging.
        case suppress(SkipReason)
    }

    /// Classifies a pasteboard snapshot from the full UTI list of its first item.
    ///
    /// Must see the *unfiltered* type list (markers included), so call it before
    /// `shouldSkipBeforeReading` strips the `org.nspasteboard.*` reps. Precedence:
    /// a Transient or AutoGenerated marker suppresses the whole snapshot (it is
    /// throwaway or unintended) even when a Concealed marker is also present; a
    /// Concealed marker alone conceals; otherwise the snapshot is allowed.
    public static func disposition(forTypes utis: [String]) -> SnapshotDisposition {
        if utis.contains(transientMarkerUTI) {
            return .suppress(.transientSnapshot)
        }
        if utis.contains(autoGeneratedMarkerUTI) {
            return .suppress(.autoGeneratedSnapshot)
        }
        if utis.contains(concealedMarkerUTI) {
            return .conceal
        }
        return .allow
    }

    /// `true` for types excluded by identity alone (`transientMarkerType` /
    /// `fileReferenceType`).
    ///
    /// Callable before reading any data so these skips cost nothing —
    /// intake sites should filter their type lists with this first, then
    /// read data only for the survivors.
    public static func shouldSkipBeforeReading(uti: String) -> Bool {
        skipReasonBeforeReading(uti: uti) != nil
    }

    /// Returns only the representations that are safe to apply to a pasteboard.
    ///
    /// Receive-side enforcement, symmetric with the send-side `evaluate(_:)`:
    /// compliant peers already filter at snapshot time, so anything caught here
    /// came from a buggy or malicious peer. It (1) drops the identity skips —
    /// without it a crafted payload could smuggle e.g. a `public.file-url` onto
    /// the receiving pasteboard behind a visible image representation — and
    /// (2) drops empty representations. Sizes are no longer gated: a streamed
    /// representation is bounded by free disk space, not a fixed cap.
    public static func sanitizedForApply(
        _ representations: [ClipboardContent.Representation]
    ) -> [ClipboardContent.Representation] {
        representations.filter { representation in
            if shouldSkipBeforeReading(uti: representation.uti) { return false }
            if representation.byteCount == 0 { return false }
            return true
        }
    }

    /// Applies every rule, in order, over (uti, data) pairs read from one pasteboard item.
    ///
    /// Operates on in-memory (uti, data) pairs read from a non-file pasteboard
    /// item — copied *files* take the disk-backed `.file` path and never pass
    /// through here. Dynamic (`dyn.*`) UTIs are deliberately kept: the encoding
    /// is a deterministic function of the original legacy type, so macOS↔macOS
    /// round-trips reproduce the exact type.
    public static func evaluate(_ raw: [(uti: String, data: Data)]) -> Outcome {
        var kept: [ClipboardContent.Representation] = []
        var skipped: [Skipped] = []

        for (uti, data) in raw {
            if let reason = skipReasonBeforeReading(uti: uti) {
                skipped.append(Skipped(uti: uti, reason: reason))
                continue
            }
            if data.isEmpty {
                skipped.append(Skipped(uti: uti, reason: .emptyData))
                continue
            }
            kept.append(ClipboardContent.Representation(uti: uti, data: data))
        }

        return Outcome(content: ClipboardContent(representations: kept), skipped: skipped)
    }

    private static func skipReasonBeforeReading(uti: String) -> SkipReason? {
        if uti.hasPrefix("org.nspasteboard.") {
            return .transientMarkerType
        }
        if uti == "public.file-url"
            || uti.hasPrefix("com.apple.pasteboard.promised-file")
            || uti.hasPrefix("com.apple.NSFilePromise")
            || uti == "NSFilenamesPboardType"
        {
            return .fileReferenceType
        }
        return nil
    }
}
