import Foundation

/// The single policy deciding which pasteboard representations may cross the
/// clipboard channel.
///
/// Shared by every intake site — the guest agent's pasteboard poll and the host
/// window's Paste/drag gestures — so both ends apply identical filtering. There
/// is **no size cap**: every transfer is chunk-streamed to and from disk, so
/// what the rules cover is identity skips — representation types that must never
/// be sent or applied — plus the empty-payload skip.
public enum ClipboardSnapshotPolicy {
    /// Why a representation was excluded from a snapshot.
    public enum SkipReason: Equatable, Sendable {
        /// An `org.nspasteboard.*` marker representation dropped from a synced
        /// payload: the markers are metadata flags, not content, so their bytes
        /// never cross while the content alongside them still does — unless the
        /// whole snapshot is suppressed (`transientSnapshot` /
        /// `autoGeneratedSnapshot`).
        case transientMarkerType

        /// File URLs, file promises, and legacy filename lists name host-side
        /// filesystem locations that are meaningless — or misleading — inside the
        /// guest, and promises need a sender-side callback flow that cannot cross
        /// the wire.
        case fileReferenceType

        /// Zero-byte representations carry no information.
        case emptyData

        /// The whole snapshot was dropped because it carried an
        /// `org.nspasteboard.TransientType` marker — content the source app will
        /// restore or replace within seconds (a clipboard manager re-injecting a
        /// past entry, a TextExpander/Keyboard Maestro expansion), never a
        /// deliberate copy.
        case transientSnapshot

        /// The whole snapshot was dropped because it carried an
        /// `org.nspasteboard.AutoGeneratedType` marker — content an app placed
        /// with no copy intent (e.g. a Grammarly correction) that clipboard
        /// managers ignore by convention.
        case autoGeneratedSnapshot
    }

    /// One excluded representation and the rule that excluded it.
    public struct Skipped: Equatable, Sendable {
        /// The excluded representation's UTI.
        public let uti: String

        /// The rule that excluded it.
        public let reason: SkipReason

        /// Creates a skip record.
        public init(uti: String, reason: SkipReason) {
            self.uti = uti
            self.reason = reason
        }
    }

    /// Result of evaluating a raw pasteboard snapshot.
    ///
    /// Never silently empty: when the input was non-empty but `content`
    /// is, `skipped` records why every representation was excluded.
    public struct Outcome: Sendable {
        /// The representations that survived every rule.
        public let content: ClipboardContent

        /// The representations excluded, with reasons.
        public let skipped: [Skipped]
    }

    // MARK: - Marker types

    /// `org.nspasteboard.TransientType` — the source app will restore or replace
    /// the pasteboard within seconds; the content is never a deliberate copy.
    public static let transientMarkerUTI = "org.nspasteboard.TransientType"

    /// `org.nspasteboard.AutoGeneratedType` — content placed with no copy intent
    /// (e.g. a Grammarly correction); not something the user expects to paste.
    public static let autoGeneratedMarkerUTI = "org.nspasteboard.AutoGeneratedType"

    /// `org.nspasteboard.ConcealedType` — confidential content (password
    /// managers), synced so it can still be pasted but hidden from the host
    /// clipboard window's display.
    public static let concealedMarkerUTI = "org.nspasteboard.ConcealedType"

    /// What to do with an entire pasteboard snapshot, decided from its
    /// `org.nspasteboard.*` marker types before any data is read.
    public enum SnapshotDisposition: Equatable, Sendable {
        /// Sync the snapshot normally (still subject to per-representation
        /// filtering via `evaluate`).
        case allow

        /// Sync the snapshot but mark its `ClipboardContent` concealed, so the
        /// host clipboard window hides it behind a placeholder while the bytes
        /// still cross to be pasted into the peer.
        case conceal

        /// Drop the entire snapshot so nothing crosses; the reason distinguishes
        /// the transient and auto-generated markers for user-facing messaging.
        case suppress(SkipReason)
    }

    /// Classifies a pasteboard snapshot from the full UTI list of its first item.
    ///
    /// Must see the *unfiltered* type list (markers included), so call it before
    /// `shouldSkipBeforeReading` strips the `org.nspasteboard.*` reps.
    public static func disposition(forTypes utis: [String]) -> SnapshotDisposition {
        if utis.contains(transientMarkerUTI) {
            return .suppress(.transientSnapshot)
        }
        if utis.contains(autoGeneratedMarkerUTI) {
            return .suppress(.autoGeneratedSnapshot)
        }
        if utis.contains(concealedMarkerUTI) {
            return .conceal
        }
        return .allow
    }

    /// `true` for types excluded by identity alone (`transientMarkerType` /
    /// `fileReferenceType`).
    ///
    /// Intake sites filter their type lists with this first and read data only
    /// for the survivors, so these skips cost nothing.
    public static func shouldSkipBeforeReading(uti: String) -> Bool {
        skipReasonBeforeReading(uti: uti) != nil
    }

    /// Applies every rule, in order, over (uti, data) pairs read from one pasteboard item.
    ///
    /// Copied *files* take the disk-backed `.file` path and never pass through
    /// here. Dynamic (`dyn.*`) UTIs are deliberately kept: the encoding is a
    /// deterministic function of the original legacy type, so macOS↔macOS
    /// round-trips reproduce the exact type.
    public static func evaluate(_ raw: [(uti: String, data: Data)]) -> Outcome {
        var kept: [ClipboardContent.Representation] = []
        var skipped: [Skipped] = []

        for (uti, data) in raw {
            if let reason = skipReasonBeforeReading(uti: uti) {
                skipped.append(Skipped(uti: uti, reason: reason))
                continue
            }
            if data.isEmpty {
                skipped.append(Skipped(uti: uti, reason: .emptyData))
                continue
            }
            kept.append(ClipboardContent.Representation(uti: uti, data: data))
        }

        return Outcome(content: ClipboardContent(representations: kept), skipped: skipped)
    }

    private static func skipReasonBeforeReading(uti: String) -> SkipReason? {
        if uti.hasPrefix("org.nspasteboard.") {
            return .transientMarkerType
        }
        if uti == "public.file-url"
            || uti.hasPrefix("com.apple.pasteboard.promised-file")
            || uti.hasPrefix("com.apple.NSFilePromise")
            || uti == "NSFilenamesPboardType"
        {
            return .fileReferenceType
        }
        return nil
    }
}
