import AppKit
import Foundation
import KernovaTestSupport
import Testing
import UniformTypeIdentifiers

@testable import KernovaKit

@Suite("ClipboardPasteboardReader", .admissionGated)
@MainActor
struct ClipboardPasteboardReaderTests {
    // MARK: - Fixtures

    /// A unique scratch directory the caller removes when the test ends.
    private func makeScratch() throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("reader-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private func fileURLItem(_ url: URL) -> FakePasteboardItem {
        FakePasteboardItem([(type: .fileURL, data: Data(url.absoluteString.utf8))])
    }

    private static let promisedFileURLType = NSPasteboard.PasteboardType(
        "com.apple.pasteboard.promised-file-url")
    private static let promisedFileNameType = NSPasteboard.PasteboardType(
        "com.apple.pasteboard.promised-file-content-type")

    // MARK: - Markers

    @Test(
        "a transient or auto-generated marker suppresses the whole snapshot, naming which",
        arguments: [
            ClipboardSnapshotPolicy.transientMarkerUTI,
            ClipboardSnapshotPolicy.autoGeneratedMarkerUTI,
        ])
    func markerSuppressesSnapshot(marker: String) {
        let pasteboard = FakeReadPasteboard()
        // A real password/expansion item carries the marker alongside content;
        // the whole snapshot goes, not just the marker rep.
        pasteboard.setItem([
            (type: NSPasteboard.PasteboardType(marker), data: Data([1])),
            (type: .string, data: Data("noise".utf8)),
        ])

        guard
            case .suppressed(let reason) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .suppressed")
            return
        }
        #expect(
            reason
                == (marker == ClipboardSnapshotPolicy.transientMarkerUTI
                    ? .transientSnapshot : .autoGeneratedSnapshot))
    }

    @Test("a concealed marker still crosses, flagged, with the marker rep dropped")
    func concealedMarkerFlagsContent() {
        let pasteboard = FakeReadPasteboard()
        pasteboard.setItem([
            (
                type: NSPasteboard.PasteboardType(ClipboardSnapshotPolicy.concealedMarkerUTI),
                data: Data([1])
            ),
            (type: .string, data: Data("hunter2".utf8)),
        ])

        guard
            case .content(let content, let skipped) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .content")
            return
        }
        #expect(content.isConcealed)
        #expect(skipped == 0)
        #expect(content.representations.map(\.uti) == [NSPasteboard.PasteboardType.string.rawValue])
    }

    // MARK: - File classification

    @Test("a promised file URL already written on disk resolves like a concrete one")
    func promisedFileURLResolves() throws {
        let scratch = try makeScratch()
        defer { try? FileManager.default.removeItem(at: scratch) }
        let file = scratch.appendingPathComponent("promised.txt")
        try Data("body".utf8).write(to: file)

        let pasteboard = FakeReadPasteboard()
        pasteboard.setItems([
            FakePasteboardItem([
                (type: Self.promisedFileURLType, data: Data(file.absoluteString.utf8))
            ])
        ])

        guard
            case .pendingFiles(let urls, let unresolved) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .pendingFiles")
            return
        }
        #expect(urls == [file])
        #expect(unresolved == 0)
    }

    @Test("a copied file deleted since is a loss, never its path as text")
    func vanishedFileIsALossNotItsPath() {
        let gone = URL(fileURLWithPath: "/nonexistent/\(UUID().uuidString)/notes.txt")
        let pasteboard = FakeReadPasteboard()
        pasteboard.setItem([
            (type: .fileURL, data: Data(gone.absoluteString.utf8)),
            // Finder pairs the URL with the path as text; it is the file's
            // descriptor, not content the copy meant to carry.
            (type: .string, data: Data(gone.path.utf8)),
            (type: .URL, data: Data(gone.absoluteString.utf8)),
        ])

        guard
            case .nothingOfferable(let lost, let unreadable) =
                ClipboardPasteboardReader
                .readSnapshot(from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .nothingOfferable")
            return
        }
        #expect(lost == 1)
        #expect(unreadable)
    }

    @Test("a plain text snapshot names no file, so nothing is counted lost")
    func textSnapshotIsNotAFile() {
        let pasteboard = FakeReadPasteboard()
        pasteboard.setItem([(type: .string, data: Data("hello".utf8))])

        guard
            case .content(let content, let skipped) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .content")
            return
        }
        #expect(skipped == 0)
        #expect(content.representations.map(\.uti) == [NSPasteboard.PasteboardType.string.rawValue])
    }

    @Test("a missed URL is not a loss while a promise is still outstanding")
    func outstandingPromiseIsNotALoss() {
        let gone = URL(fileURLWithPath: "/nonexistent/\(UUID().uuidString)/pending.txt")
        let pasteboard = FakeReadPasteboard()
        // The promise advertises a file still to be written, so its URL missing
        // today says nothing; `NSFilePromiseReceiver` can still deliver it.
        pasteboard.setItems([
            FakePasteboardItem(
                types: [.fileURL, Self.promisedFileNameType],
                bytes: [.fileURL: Data(gone.absoluteString.utf8)])
        ])

        guard
            case .nothingOfferable(let lost, _) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .nothingOfferable")
            return
        }
        #expect(lost == 0)
    }

    @Test("a file drag's inline flavor stands in for item 0's lost file, so nothing is reported")
    func firstItemInlineFlavorStandsInForItsLostFile() throws {
        let gone = URL(fileURLWithPath: "/nonexistent/\(UUID().uuidString)/shot.png")
        let png = try makePNG()
        let pasteboard = FakeReadPasteboard()
        // A screenshot drag pairs the image bytes with a `.fileURL` whose file
        // is already gone — the image is what the gesture carried.
        pasteboard.setItem([
            (type: .png, data: png),
            (type: .fileURL, data: Data(gone.absoluteString.utf8)),
        ])

        guard
            case .content(let content, let skipped) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .content")
            return
        }
        #expect(skipped == 0)
        #expect(content.representations.map(\.uti) == [NSPasteboard.PasteboardType.png.rawValue])
    }

    @Test("a lost file on a later item has nothing standing in for it, so it is reported")
    func laterItemsLostFileIsReported() throws {
        let png = try makePNG()
        let gone = URL(fileURLWithPath: "/nonexistent/\(UUID().uuidString)/gone.txt")
        let pasteboard = FakeReadPasteboard()
        pasteboard.setItems([
            FakePasteboardItem([(type: .png, data: png)]),
            FakePasteboardItem([(type: .fileURL, data: Data(gone.absoluteString.utf8))]),
        ])

        guard
            case .content(_, let skipped) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .content")
            return
        }
        #expect(skipped == 1)
    }

    // MARK: - Text-only transports

    @Test("a resolvable file is deferred whatever the transport carries")
    func textOnlyTransportDefersAResolvableFile() throws {
        let scratch = try makeScratch()
        defer { try? FileManager.default.removeItem(at: scratch) }
        let file = scratch.appendingPathComponent("notes.txt")
        try Data("body".utf8).write(to: file)

        let pasteboard = FakeReadPasteboard()
        pasteboard.setItems([fileURLItem(file)])

        // The file resolves, so the refusal is the resolve stage's — the
        // snapshot stage defers it like any other file.
        guard
            case .pendingFiles = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: false)
        else {
            Issue.record("Expected .pendingFiles")
            return
        }
    }

    @Test("a text-only transport refuses a snapshot whose file is gone")
    func textOnlyTransportRefusesAVanishedFile() {
        let gone = URL(fileURLWithPath: "/nonexistent/\(UUID().uuidString)/notes.txt")
        let pasteboard = FakeReadPasteboard()
        pasteboard.setItem([
            (type: .fileURL, data: Data(gone.absoluteString.utf8)),
            (type: .string, data: Data(gone.path.utf8)),
        ])

        guard
            case .textOnlyRefusal = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: false)
        else {
            Issue.record("Expected .textOnlyRefusal")
            return
        }
    }

    @Test("a text-only transport takes plain text")
    func textOnlyTransportTakesText() {
        let pasteboard = FakeReadPasteboard()
        pasteboard.setItem([(type: .string, data: Data("hello".utf8))])

        guard
            case .content(let content, _) = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: false)
        else {
            Issue.record("Expected .content")
            return
        }
        #expect(content.representations.map(\.uti) == [ClipboardContent.utf8TextUTI])
    }

    // MARK: - Empty

    @Test("a pasteboard holding no item at all is empty, not a loss")
    func emptyPasteboard() {
        let pasteboard = FakeReadPasteboard()

        guard
            case .empty = ClipboardPasteboardReader.readSnapshot(
                from: pasteboard, allowsBinary: true)
        else {
            Issue.record("Expected .empty")
            return
        }
    }

    // MARK: - Resolving files

    @Test("a symlink crosses as its target's bytes under the name that was copied")
    func symlinkResolvesToTargetUnderTheCopiedName() throws {
        let scratch = try makeScratch()
        defer { try? FileManager.default.removeItem(at: scratch) }
        let target = scratch.appendingPathComponent("target.txt")
        try Data("target body".utf8).write(to: target)
        let link = scratch.appendingPathComponent("link.txt")
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: target)

        let intake = ClipboardPasteboardReader.resolve(filesAt: [link])

        #expect(intake.skipped == 0)
        let rep = try #require(intake.representations.first)
        #expect(rep.filename == "link.txt")
        #expect(rep.byteCount == Data("target body".utf8).count)
    }

    @Test("a file this process cannot open is skipped, not offered as an empty one")
    func unreadableFileIsSkipped() throws {
        let scratch = try makeScratch()
        defer { try? FileManager.default.removeItem(at: scratch) }
        let readable = scratch.appendingPathComponent("readable.txt")
        try Data("body".utf8).write(to: readable)
        let sealed = scratch.appendingPathComponent("sealed.txt")
        try Data("secret".utf8).write(to: sealed)
        try FileManager.default.setAttributes([.posixPermissions: 0], ofItemAtPath: sealed.path)
        defer {
            try? FileManager.default.setAttributes(
                [.posixPermissions: 0o644], ofItemAtPath: sealed.path)
        }

        let intake = ClipboardPasteboardReader.resolve(filesAt: [readable, sealed])

        #expect(intake.representations.map(\.filename) == ["readable.txt"])
        #expect(intake.skipped == 1)
    }

    @Test("the snapshot's own unresolved count is folded into the resolve stage's")
    func unresolvedCountIsFoldedIn() throws {
        let scratch = try makeScratch()
        defer { try? FileManager.default.removeItem(at: scratch) }
        let file = scratch.appendingPathComponent("kept.txt")
        try Data("body".utf8).write(to: file)

        let intake = ClipboardPasteboardReader.resolve(filesAt: [file], unresolved: 2)

        #expect(intake.representations.count == 1)
        #expect(intake.skipped == 2)
    }

    @Test("a folder becomes a directory source rep sized by the injected walk")
    func folderBecomesADirectorySourceRep() throws {
        let scratch = try makeScratch()
        defer { try? FileManager.default.removeItem(at: scratch) }
        let folder = scratch.appendingPathComponent("Tree", isDirectory: true)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)

        let intake = ClipboardPasteboardReader.resolve(filesAt: [folder], sizeOf: { _ in 4_096 })

        let rep = try #require(intake.representations.first)
        #expect(rep.isDirectory)
        #expect(rep.filename == "Tree")
        #expect(rep.byteCount == 4_096)
    }

    // MARK: - Helpers

    private func makePNG() throws -> Data {
        let rep = try #require(
            NSBitmapImageRep(
                bitmapDataPlanes: nil, pixelsWide: 2, pixelsHigh: 2,
                bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0
            ))
        return try #require(rep.representation(using: .png, properties: [:]))
    }
}
